### ISSUE TITLE
Research on docker and how we can utilize it 

### ISSUE THREAD

**Issue by Seonin** [Code9Developers/Integration#25]
# Possible solutions

@SirJosh  recommended that we split up the docker implementation into 3 containers:

- The first container will contain the server and front end 
- The second container will contain the AI that will get the required employees
- The third container will contain the database 

So each part will be containerized in docker and communicate through ports **(I assume)**

_This is not a concrete strategy it is just a suggestion that Josh and I talked about briefly today_

**Comment by Seonin** [comment]
https://www.digitalocean.com/community/tutorials/how-to-deploy-a-node-js-and-mongodb-application-with-rancher-on-ubuntu-14-04

**Comment by Seonin** [comment]
That could possibly be something we could look into but later on...It has a whole lot of stuff on how to set up a nodejs and mongo container

**Comment by Seonin** [comment]
[http://www.ifdattic.com/how-to-mongodb-nodejs-docker/](url)

**Comment by SirJosh** [comment]
I have run a test docker set up where I containerised the backend. So far it works well. Will let you guys know in the future when we get to this.
